### ISSUE TITLE
Object Page: `:id` in path is breaking on windows

### ISSUE THREAD

**Issue by jLouzado** [milli-consortium/milli-frontend#15]
# Steps

* be on a Windows machine
* load `/search`, perform a search via the search bar, and click on one of the cards
* page will navigate to `/entities/:id`

# Observation

![illegal-path-win32](https://user-images.githubusercontent.com/6399323/120791227-8dfb1f80-c551-11eb-9938-ee3116eef32b.png)

# Potential solutions

* https://github.com/jamhall/s3rver/issues/390
* https://stackoverflow.com/questions/54708276/gatsby-contains-invalid-win32-path-characters
* https://github.com/gatsbyjs/gatsby/issues/13965

**Comment by bartosjiri** [comment]
@jLouzado Encountered similar issue, this might help: https://github.com/gatsbyjs/gatsby/issues/31791

**Comment by salus-sage** [comment]
issue resolved by updating the path in gatsby-node.js
